### ISSUE TITLE
代码中抛出异常类型的问题

### ISSUE THREAD

**Issue by jiangll007** [rocketmq/rocketmq-console#13]
你好，down下来代码后，本地代码检查软件会检查出工程中的service类不少方法抛出的异常过大的问题。比如clusterService.list 抛出了 Throwable. 从实现来看，寻根追底到rocketmq的实现，rocketmq的方法抛出的异常也就是Exception级别的 。为什么封装一层后确抛出了Throwable级别的异常。因为这个会导致“Catching either Throwable or Error will also catch OutOfMemoryError and InternalError, from which an application should not attempt to recover”

**Comment by yankai913** [comment]
你好，我又看了下clusterService.list，发现这个方法确实把异常扩大了，这里抛出RuntimeException的子类更合适，方便它的调用方捕获。

英文说的应该是另外一层意思，即在catch时不应该用Throwable，因为这样会捕获OutOfMemoryError和InternalError，这种Error捕获到也没用，程序处理不了。你贴的这句英文应该只是warning吧。

这里已知try里面的异常，用Exception捕获更准确，当然用Throwable捕获也没问题。如果回答的不准确，还请纠正。

2016-08-08 17:48 GMT+08:00 a304507016 <notifications@github.com>:

**Comment by jiangll007** [comment]
搜了下这个问题 ，也没有查到抛出更高级别的异常有什么特别不好的地方。 一般来说 如果是想抓取系统级别的异常（Error），那么证明是开发人员想自己处理异常。
